#!/usr/bin/env bash
#
# Deploy DopaX to Azure. Idempotent: run it as many times as you like.
#
#   ./infra/deploy.sh                 data layer and the Jenkins build server
#   ./infra/deploy.sh --no-jenkins    data layer only, no build server
#   ./infra/deploy.sh --with-apps     also build images and deploy the apps
#   ./infra/deploy.sh --what-if       show what would change, write nothing
#
# The first run of a fresh subscription takes roughly 15 to 20 minutes, most of
# it waiting on PostgreSQL Flexible Server to provision.
#
# This script never runs the R5 data bootstrap. That is a deliberate, separate,
# and observed step — see the runbook in infra/README.md.
#
# --with-apps is phase 2 and does not work yet. The backend cannot start against
# an Azure storage backend until src/storage/ exists and the env schema moves to
# managed identity; see "Known gaps" in infra/README.md. The flag is wired so
# the path is reviewable, not because it is ready.

set -euo pipefail

readonly REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly SECRETS_FILE="${REPO_ROOT}/infra/.secrets.env"

LOCATION="${DOPAX_LOCATION:-israelcentral}"
ENVIRONMENT="${DOPAX_ENVIRONMENT:-prod}"
RESOURCE_GROUP="${DOPAX_RESOURCE_GROUP:-dopax-${ENVIRONMENT}-rg}"
IMAGE_TAG="${DOPAX_IMAGE_TAG:-$(git -C "${REPO_ROOT}" rev-parse --short HEAD 2>/dev/null || echo latest)}"

WITH_APPS=false
WHAT_IF=false
DEPLOY_JENKINS=true
for arg in "$@"; do
  case "$arg" in
    --with-apps)  WITH_APPS=true ;;
    --no-jenkins) DEPLOY_JENKINS=false ;;
    --data-only)  WITH_APPS=false ;;   # the default; accepted for clarity
    --what-if)    WHAT_IF=true ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
warn() { printf '\033[33mwarning: %s\033[0m\n' "$*" >&2; }
fail() { printf '\033[31merror: %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Preflight
# ---------------------------------------------------------------------------
#
# Docker is checked later, and only when images are actually built. The data
# layer needs no local daemon.

command -v az >/dev/null || fail "azure-cli is not installed. brew install azure-cli"

az account show >/dev/null 2>&1 || fail "not signed in. Run: az login"

SUBSCRIPTION="$(az account show --query name -o tsv)"
SUBSCRIPTION_ID="$(az account show --query id -o tsv)"

log "Target"
echo "  subscription   ${SUBSCRIPTION} (${SUBSCRIPTION_ID})"
echo "  resource group ${RESOURCE_GROUP}"
echo "  location       ${LOCATION}"
echo "  build server   ${DEPLOY_JENKINS}"
echo "  applications   ${WITH_APPS}"
[[ "${WITH_APPS}" == true ]] && echo "  image tag      ${IMAGE_TAG}"

# ---------------------------------------------------------------------------
# Secrets
# ---------------------------------------------------------------------------
#
# Generated once and kept out of git. They are the source of truth for
# redeployment: Bicep needs the same PostgreSQL password on every run, and
# rotating JWT_SECRET would invalidate every signed-in participant session,
# which guardrail R1 forbids.

if [[ ! -f "${SECRETS_FILE}" ]]; then
  log "Generating deployment secrets → infra/.secrets.env"
  umask 077
  cat > "${SECRETS_FILE}" <<EOF
# Generated by infra/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Gitignored. Back this up somewhere your team can reach: losing
# JWT_SECRET signs every participant out, which guardrail R1 forbids.
POSTGRES_ADMIN_PASSWORD='$(openssl rand -base64 24 | tr -d '/+=' | head -c 28)'
JWT_SECRET='$(openssl rand -hex 32)'
ADMIN_JWT_SECRET='$(openssl rand -hex 32)'
JENKINS_ADMIN_PASSWORD='$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)'
EOF
  echo "  wrote ${SECRETS_FILE}"
fi

# shellcheck disable=SC1090
source "${SECRETS_FILE}"

: "${POSTGRES_ADMIN_PASSWORD:?missing in infra/.secrets.env}"
: "${JWT_SECRET:?missing in infra/.secrets.env}"
: "${ADMIN_JWT_SECRET:?missing in infra/.secrets.env}"

[[ "${JWT_SECRET}" != "${ADMIN_JWT_SECRET}" ]] \
  || fail "JWT_SECRET and ADMIN_JWT_SECRET must differ; the backend refuses to start otherwise"

# Added after the first version of this script, so an existing secrets file
# will not have it. Append rather than regenerate: rewriting the file would
# roll JWT_SECRET.
if [[ "${DEPLOY_JENKINS}" == true && -z "${JENKINS_ADMIN_PASSWORD:-}" ]]; then
  log "Adding JENKINS_ADMIN_PASSWORD to infra/.secrets.env"
  JENKINS_ADMIN_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
  printf "JENKINS_ADMIN_PASSWORD='%s'\n" "${JENKINS_ADMIN_PASSWORD}" >> "${SECRETS_FILE}"
fi

# ---------------------------------------------------------------------------
# Build server inputs
# ---------------------------------------------------------------------------

JENKINS_SSH_KEY=''
ALLOWED_IPS_JSON='[]'

if [[ "${DEPLOY_JENKINS}" == true ]]; then
  # SSH key. An existing key is reused rather than a new one minted, because a
  # dedicated key nobody has in their agent is a key nobody can use in a hurry.
  SSH_KEY_FILE="${DOPAX_SSH_PUBLIC_KEY_FILE:-}"
  if [[ -z "${SSH_KEY_FILE}" ]]; then
    for candidate in "${HOME}/.ssh/id_ed25519.pub" "${HOME}/.ssh/id_rsa.pub"; do
      [[ -f "${candidate}" ]] && { SSH_KEY_FILE="${candidate}"; break; }
    done
  fi
  [[ -n "${SSH_KEY_FILE}" && -f "${SSH_KEY_FILE}" ]] \
    || fail "no SSH public key found. Generate one with 'ssh-keygen -t ed25519', or set DOPAX_SSH_PUBLIC_KEY_FILE"
  JENKINS_SSH_KEY="$(< "${SSH_KEY_FILE}")"

  # Allowlist. Jenkins holds push rights to the registry that serves
  # participant data, so this is never allowed to default to the internet.
  if [[ -n "${DOPAX_ALLOWED_IPS:-}" ]]; then
    ALLOWED_IPS="${DOPAX_ALLOWED_IPS}"
  else
    DETECTED_IP="$(curl -fsS --max-time 10 https://api.ipify.org 2>/dev/null || true)"
    [[ -n "${DETECTED_IP}" ]] \
      || fail "could not detect your public IP. Set DOPAX_ALLOWED_IPS='1.2.3.4/32' explicitly"
    ALLOWED_IPS="${DETECTED_IP}/32"
  fi

  # Comma-separated CIDRs to a JSON array, for --parameters.
  ALLOWED_IPS_JSON="$(printf '%s' "${ALLOWED_IPS}" | awk -F, '{
    printf "["
    for (i = 1; i <= NF; i++) printf "%s\"%s\"", (i > 1 ? "," : ""), $i
    printf "]"
  }')"

  log "Build server"
  echo "  ssh key        ${SSH_KEY_FILE}"
  echo "  allowed from   ${ALLOWED_IPS}"
  echo
  echo "  Only these addresses will reach Jenkins on 443 and 22. Add more with"
  echo "  DOPAX_ALLOWED_IPS='1.2.3.4/32,5.6.7.8/32' and rerun."
fi

# ---------------------------------------------------------------------------
# Resource group
# ---------------------------------------------------------------------------

log "Resource group"
az group create \
  --name "${RESOURCE_GROUP}" \
  --location "${LOCATION}" \
  --tags project=dopax environment="${ENVIRONMENT}" dataClassification=phi \
  --output none
echo "  ${RESOURCE_GROUP} ready"

deploy_data() {
  local mode="${1:-create}"
  shift || true
  az deployment group "${mode}" \
    --resource-group "${RESOURCE_GROUP}" \
    --name main \
    --template-file "${REPO_ROOT}/infra/main.bicep" \
    --parameters \
      location="${LOCATION}" \
      environment="${ENVIRONMENT}" \
      postgresAdminPassword="${POSTGRES_ADMIN_PASSWORD}" \
      jwtSecret="${JWT_SECRET}" \
      adminJwtSecret="${ADMIN_JWT_SECRET}" \
      deployJenkins="${DEPLOY_JENKINS}" \
      jenkinsAdminPassword="${JENKINS_ADMIN_PASSWORD:-}" \
      jenkinsSshPublicKey="${JENKINS_SSH_KEY}" \
      jenkinsAllowedSourceIps="${ALLOWED_IPS_JSON}" \
    "$@"
}

if [[ "${WHAT_IF}" == true ]]; then
  log "What-if (no changes will be made)"
  deploy_data what-if
  exit 0
fi

# ---------------------------------------------------------------------------
# Data layer and build server
# ---------------------------------------------------------------------------

log "Deploying the data layer (this is the slow one — PostgreSQL takes ~10 min)"
deploy_data create --output none

output() {
  az deployment group show \
    --resource-group "${RESOURCE_GROUP}" --name main \
    --query "properties.outputs.${1}.value" -o tsv
}

REGISTRY_NAME="$(output registryName)"
REGISTRY_SERVER="$(output registryLoginServer)"

echo "  registry ${REGISTRY_SERVER}"

if [[ "${DEPLOY_JENKINS}" == true ]]; then
  JENKINS_URL="$(output jenkinsUrl)"
  JENKINS_VAULT="$(output jenkinsVaultName)"

  log "Build server"
  echo "  ${JENKINS_URL}"
  echo
  echo "  cloud-init takes another 3 to 5 minutes after the VM reports ready."
  echo "  Username: admin"
  echo "  Password: az keyvault secret show --vault-name ${JENKINS_VAULT} \\"
  echo "              --name jenkins-admin-password --query value -o tsv"
  echo
  echo "  The certificate is issued by Caddy's local CA, so the browser will"
  echo "  warn once. See 'Known trade-off' in infra/README.md."
fi

if [[ "${WITH_APPS}" != true ]]; then
  log "Done — data layer deployed"
  echo "  The API and staff console are phase 2. Rerun with --with-apps once"
  echo "  the backend gaps in infra/README.md are closed."
  exit 0
fi

# ---------------------------------------------------------------------------
# Images
# ---------------------------------------------------------------------------
#
# Built server-side with `az acr build`, not locally. Container Registry builds
# for the target platform, which removes the arm64 image that pushes fine from
# an Apple Silicon laptop and then fails at start with an exec format error.

log "Building images in the registry"

build_image() {
  local context="$1" target="$2" repo="$3"
  shift 3
  echo "  building ${repo}:${IMAGE_TAG} (${target})"
  az acr build \
    --registry "${REGISTRY_NAME}" \
    --platform linux/amd64 \
    --target "${target}" \
    --image "${repo}:${IMAGE_TAG}" \
    --image "${repo}:latest" \
    "$@" \
    --file "${REPO_ROOT}/${context}/Dockerfile" \
    "${REPO_ROOT}/${context}"
}

build_image backend runtime dopax-backend
build_image backend release dopax-backend-release
build_image admin   runtime dopax-admin \
  --build-arg "NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY:-}"

# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------

log "Deploying applications"
az deployment group create \
  --resource-group "${RESOURCE_GROUP}" \
  --name apps \
  --template-file "${REPO_ROOT}/infra/apps.bicep" \
  --parameters \
    location="${LOCATION}" \
    environment="${ENVIRONMENT}" \
    imageTag="${IMAGE_TAG}" \
    registryLoginServer="${REGISTRY_SERVER}" \
    identityResourceId="$(output identityResourceId)" \
    identityClientId="$(output identityClientId)" \
    databaseUrlSecretUri="$(output databaseUrlSecretUri)" \
    jwtSecretUri="$(output jwtSecretUri)" \
    adminJwtSecretUri="$(output adminJwtSecretUri)" \
    storageAccountName="$(output storageAccountName)" \
    uploadsContainerName="$(output uploadsContainerName)" \
    logAnalyticsWorkspaceId="$(output logAnalyticsWorkspaceId)" \
    legacyDriveFolderId="${DOPAX_LEGACY_DRIVE_FOLDER_ID:-}" \
  --output none

APP_URL="$(az deployment group show -g "${RESOURCE_GROUP}" -n apps \
  --query properties.outputs.apiUrl.value -o tsv)"
ADMIN_URL="$(az deployment group show -g "${RESOURCE_GROUP}" -n apps \
  --query properties.outputs.adminUrl.value -o tsv)"

log "Deployed"
echo "  API    ${APP_URL}"
echo "  admin  ${ADMIN_URL}"
echo
echo "  Health:    curl ${APP_URL}/healthz"
echo "  Readiness: curl ${APP_URL}/readyz     (expect bootstrap: pending)"
echo
echo "  /readyz reports bootstrap pending until the R5 import has run. That is a"
echo "  separate, observed step — see infra/README.md."
echo
echo "  Then grant yourself staff access before the console will let you in:"
echo
echo "    cd backend && npm run staff:add -- --email you@example.com --role admin"
